Repository Azure/data-landing-zone, pull requests merged in 2021-11, with the labels that each got.

#204 Updated Codeowners
  .github/CODEOWNERS
Labels: enhancement, committed

#205 Updated Azure CLI Version
  .github/workflows/dataLandingZoneDeployment.yml
Labels: bug, committed

#206 updated param files for GitHub and ADO deployment
  docs/EnterpriseScaleAnalytics-AzureDevOpsDeployment.md
  docs/EnterpriseScaleAnalytics-GitHubActionsDeployment.md
Labels: documentation

#209 Azure CLI Action Bugfix
  .github/workflows/dataLandingZoneDeployment.yml
Labels: bug, committed

#211 Updated Portal UI based on Feedback
  docs/reference/portal.dataLandingZone.json
Labels: feature, committed
