Repository Azure/data-landing-zone, pull requests merged in 2021-09, with the labels that each got.

#172 Updated PrivateDnsZoneGroups Names
  infra/main.json
  infra/modules/services/datafactoryruntime.bicep
  infra/modules/services/datafactorysharedintegration.bicep
  infra/modules/services/eventhubnamespace.bicep
  infra/modules/services/externalstorage.bicep
  infra/modules/services/keyvault.bicep
  infra/modules/services/mysql.bicep
  infra/modules/services/sql.bicep
  infra/modules/services/storage.bicep
  infra/modules/services/synapse.bicep
Labels: enhancement

#174 Updated Portal Vnet Validation
  docs/reference/portal.dataLandingZone.json
Labels: enhancement

#175 Adding Outputs for Network Services
  infra/main.bicep
  infra/main.json
  infra/modules/network.bicep
Labels: enhancement

#176 Change reference from Data Management Zone to Data Landing Zone
  docs/EnterpriseScaleAnalytics-CreateRepository.md
Labels: documentation

#178 Update to Spark 3.1
  infra/main.json
  infra/modules/services/synapse.bicep
Labels: bug

#181 Update Codeowners
  .github/CODEOWNERS
Labels: enhancement

#182 Remove Synapse Pools from default setup
  infra/main.json
  infra/modules/services/databricks.bicep
  infra/modules/services/synapse.bicep
Labels: enhancement

#183 Adding EventHub Namespace Network Rule Set
  infra/main.json
  infra/modules/services/eventhubnamespace.bicep
Labels: enhancement

#185 Fix changes in Spark Pool DynamicExecutor Allocation
  infra/modules/services/synapse.bicep
Labels: bug, enhancement
