Repository Azure/data-landing-zone, pull requests merged in 2021-12, with the labels that each got.

#216 Documented "ProvisioningDisabled" Error
  docs/EnterpriseScaleAnalytics-KnownIssues.md
Labels: documentation, committed

#214 Added SHIR Deployment via Custom Data
  .ado/workflows/dataLandingZoneDeployment.yml
  .github/linters/.arm-ttk.psd1
  .github/linters/.powershell-psscriptanalyzer.psd1
  .github/workflows/dataLandingZoneDeployment.yml
  docs/EnterpriseScaleAnalytics-AzureDevOpsDeployment.md
  docs/EnterpriseScaleAnalytics-GitHubActionsDeployment.md
  docs/reference/portal.dataLandingZone.json
  infra/main.bicep
  infra/main.json
  infra/modules/runtimes.bicep
  infra/modules/services/artifactstorage.bicep
  infra/modules/services/selfHostedIntegrationRuntime.bicep
  infra/params.dev.json
  infra/params.prod.json
  infra/params.test.json
Labels: enhancement, committed

#213 Added Purview Role Assignment & Storage Access Rules
  .github/linters/.arm-ttk.psd1
  .github/workflows/lint.yml
  docs/EnterpriseScaleAnalytics-ServicePrincipal.md
  docs/guidance/EnterpriseScaleAnalytics-DatabricksGeneral.md
  docs/guidance/EnterpriseScaleAnalytics-DatabricksManualSetup.md
  docs/guidance/EnterpriseScaleAnalytics-DatabricksScimSetup.md
  infra/main.bicep
  infra/main.json
  infra/modules/auxiliary/purviewRoleAssignmentSubscription.bicep
  infra/modules/externalstorage.bicep
  infra/modules/services/externalstorage.bicep
  infra/modules/services/storage.bicep
  infra/modules/storage.bicep
Labels: feature, committed

#217 Renaming from ESA to DMA
  README.md
  docs/DataManagementAnalytics-AzureDevOpsDeployment.md
  docs/DataManagementAnalytics-CreateRepository.md
  docs/DataManagementAnalytics-GitHubActionsDeployment.md
  docs/DataManagementAnalytics-KnownIssues.md
  docs/DataManagementAnalytics-Prerequisites.md
  docs/DataManagementAnalytics-ServicePrincipal.md
  docs/guidance/DataManagementAnalytics-DatabricksGeneral.md
  docs/guidance/DataManagementAnalytics-DatabricksManualSetup.md
  docs/guidance/DataManagementAnalytics-DatabricksScimSetup.md
  docs/images/DataManagementAnalytics.gif
  docs/images/EnterpriseScaleAnalytics.gif
  docs/reference/portal.dataLandingZone.json
  infra/main.bicep
  infra/main.json
Labels: documentation

#220 New Issue/PR Templates & New Contributors Guide
  .github/ISSUE_TEMPLATE/BUG_REPORT.md
  .github/ISSUE_TEMPLATE/BUG_REPORT.yml
  .github/ISSUE_TEMPLATE/DOCUMENTATION_ISSUE.yml
  .github/ISSUE_TEMPLATE/FEATURE_REQUEST.md
  .github/ISSUE_TEMPLATE/FEATURE_REQUEST.yml
  .github/ISSUE_TEMPLATE/config.yml
  .github/PULL_REQUEST_TEMPLATE.md
  .github/linters/.textlintrc
  CONTRIBUTING.md
  README.md
Labels: documentation, committed

#222 Updated GH Issue and PR Template Links
  .github/ISSUE_TEMPLATE/BUG_REPORT.yml
  .github/ISSUE_TEMPLATE/DOCUMENTATION_ISSUE.yml
  .github/ISSUE_TEMPLATE/FEATURE_REQUEST.yml
  .github/PULL_REQUEST_TEMPLATE.md
Labels: documentation

#221 Improving Region Availability
  .github/linters/.arm-ttk.psd1
  docs/DataManagementAnalytics-Prerequisites.md
  docs/reference/portal.dataLandingZone.json
  infra/main.json
  infra/modules/runtimes.bicep
  infra/modules/services/storage.bicep
Labels: enhancement
