Repository Azure/data-landing-zone, pull requests merged in 2022-01, with the labels that each got.

#223 Add Data Landing Zone Subs to Storage Firewall
  .github/linters/.arm-ttk.psd1
  docs/DataManagementAnalytics-AzureDevOpsDeployment.md
  docs/DataManagementAnalytics-GitHubActionsDeployment.md
  docs/reference/portal.dataLandingZone.json
  infra/main.bicep
  infra/main.json
  infra/modules/externalstorage.bicep
  infra/modules/metadata.bicep
  infra/modules/services/datafactoryruntime.bicep
  infra/modules/services/datafactorysharedintegration.bicep
  infra/modules/services/externalstorage.bicep
  infra/modules/services/storage.bicep
  infra/modules/storage.bicep
  infra/params.dev.json
  infra/params.prod.json
  infra/params.test.json
Labels: feature, committed

#224 Rename data management zone
  README.md
  docs/DataManagementAnalytics-AzureDevOpsDeployment.md
  docs/DataManagementAnalytics-GitHubActionsDeployment.md
  docs/DataManagementAnalytics-Prerequisites.md
  docs/DataManagementAnalytics-ServicePrincipal.md
  docs/reference/portal.dataLandingZone.json
  infra/main.bicep
  infra/main.json
Labels: documentation

#227 Espen/contribution_guide
  CONTRIBUTING.md
Labels: documentation

#226 Fix Portal UI Bug
  docs/reference/portal.dataLandingZone.json
Labels: bug
